// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgj-CJToL5aFBHASDYICGCio3Z-WeDMw',
    appId: '1:246419270175:web:33ec420a8fd3973f0c832a',
    messagingSenderId: '246419270175',
    projectId: 'new-wedding-hall',
    authDomain: 'new-wedding-hall.firebaseapp.com',
    storageBucket: 'new-wedding-hall.firebasestorage.app',
    measurementId: 'G-34T6CXC6RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKm_wjU3R-1AkQjPYO1PXHi4R2ZJOQnyQ',
    appId: '1:246419270175:android:42fb5efff09a3db30c832a',
    messagingSenderId: '246419270175',
    projectId: 'new-wedding-hall',
    storageBucket: 'new-wedding-hall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH7aPUVEClJZIkSdBk8BPMfS8Lr9jGOKQ',
    appId: '1:246419270175:ios:faa08ac3e116b77b0c832a',
    messagingSenderId: '246419270175',
    projectId: 'new-wedding-hall',
    storageBucket: 'new-wedding-hall.firebasestorage.app',
    iosBundleId: 'com.example.newWeddingHall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH7aPUVEClJZIkSdBk8BPMfS8Lr9jGOKQ',
    appId: '1:246419270175:ios:faa08ac3e116b77b0c832a',
    messagingSenderId: '246419270175',
    projectId: 'new-wedding-hall',
    storageBucket: 'new-wedding-hall.firebasestorage.app',
    iosBundleId: 'com.example.newWeddingHall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgj-CJToL5aFBHASDYICGCio3Z-WeDMw',
    appId: '1:246419270175:web:ac966656890bdc0f0c832a',
    messagingSenderId: '246419270175',
    projectId: 'new-wedding-hall',
    authDomain: 'new-wedding-hall.firebaseapp.com',
    storageBucket: 'new-wedding-hall.firebasestorage.app',
    measurementId: 'G-122ENPT6J6',
  );

}